### PR TITLE
Filter out empty path components

### PR DESCRIPTION
**Pull request by nehzata**

### CODE REVIEW

**Review by alecthomas — APPROVED** [review]

**Review by alecthomas — CHANGES_REQUESTED** [review]
This won't work

**Comment by alecthomas** [comment]
The routing logic below relies on parts[0] being empty

**Comment by nehzata** [comment]
Yet again I was too hopeful. hahah

**Comment by nehzata** [comment]
@alecthomas updated. How does it look now?

**Review by alecthomas — APPROVED** [review]

**Pull request merged**
